### ISSUE TITLE
Fatal error on Termux, Android 13, and on FreeBSD

### ISSUE THREAD

**Issue by piereligio** [mihir-io/MotionPhotoMuxer#11]
I'm getting this error when I install requirements. Any idea? Thanks in advance

$ python3 -m pip install -r MotionPhotoMuxer/requirements.txt
Collecting py3exiv2==0.9.3 (from -r MotionPhotoMuxer/requirements.txt (line 1))
  Using cached py3exiv2-0.9.3.tar.gz (36 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done          Building wheels for collected packages: py3exiv2
  Building wheel for py3exiv2 (pyproject.toml) ... error  error: subprocess-exited-with-error

  × Building wheel for py3exiv2 (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-39             creating build/lib.linux-aarch64-cpython-39/pyexiv2                                                             copying src/pyexiv2/init.py -> build/lib.linux-aarch64-cpython-39/pyexiv2
      copying src/pyexiv2/exif.py -> build/lib.linux-aarch64-cpython-39/pyexiv2
      copying src/pyexiv2/iptc.py -> build/lib.linux-aarch64-cpython-39/pyexiv2
      copying src/pyexiv2/metadata.py -> build/lib.linux-aarch64-cpython-39/pyexiv2
      copying src/pyexiv2/preview.py -> build/lib.linux-aarch64-cpython-39/pyexiv2                                    copying src/pyexiv2/utils.py -> build/lib.linux-aarch64-cpython-39/pyexiv2                                      copying src/pyexiv2/xmp.py -> build/lib.linux-aarch64-cpython-39/pyexiv2                                        running build_ext                                       building 'libexiv2python' extension                     creating build/temp.linux-aarch64-cpython-39            creating build/temp.linux-aarch64-cpython-39/src        aarch64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -I/data/data/com.termux/files/usr/include/python3.9 -c src/exiv2wrapper.cpp -o build/temp.linux-aarch64-cpython-39/src/exiv2wrapper.o -g
      In file included from src/exiv2wrapper.cpp:27:          src/exiv2wrapper.hpp:32:10: fatal error: 'exiv2/exiv2.hpp' file not found
      #include "exiv2/exiv2.hpp"
               ^~~~~
      1 error generated.
      error: command '/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for py3exiv2             Failed to build py3exiv2
ERROR: Could not build wheels for py3exiv2, which is required to install pyproject.toml-based projects

**Comment by piereligio** [comment]
I'm getting the same exact error on FreeBSD, whilst in Windows WSL it worked fine. I wonder if there is some additional step I'm not aware of

**Comment by mihir-io** [comment]
Thanks for reporting this, I'll look into it.

**Comment by romanovj** [comment]
fatal error: 'exiv2/exiv2.hpp' file not found
`apt-file search exiv2/exiv2.hpp`
exiv2: /data/data/com.termux/files/usr/include/exiv2/exiv2.hpp
`pkg install exiv2`

next error
error: no template named 'auto_ptr' in namespace 'std'; did you mean simply 'auto_ptr'?
`find /data/data/com.termux/files/usr/include/exiv2 | xargs -n1 sed -i s/'std::auto_ptr'/auto_ptr/g`

next error
fatal error: 'boost/python.hpp' file not found
`apt-file search boost/python.hpp   `                                          boost-headers: /data/data/com.termux/files/usr/include/boost/python.hpp
`pkg install boost-headers`

finally

**Successfully installed py3exiv2-0.9.3**

**Comment by romanovj** [comment]
pkg install exiv2
pkg install boost-headers
CFLAGS=-D_LIBCPP_ENABLE_CXX17_REMOVED_AUTO_PTR pip install py3exiv2==0.9.3

(I used clang)

**Comment by mihir-io** [comment]
@piereligio Your original issue seems to be that the `exiv2` package isn't installed.

After installing that package with `pkg install exiv2`, I ran into a new issue:

```
      /data/data/com.termux/files/usr/include/exiv2/tags.hpp:143:17: error: no template named 'auto_ptr' in namespace 'std'; did you mean simply 'auto_ptr'?
        143 |         typedef std::auto_ptr<ExifKey> AutoPtr;
            |                 ^~~~~
      /data/data/com.termux/files/usr/include/exiv2/config.h:105:3: note: 'auto_ptr' declared here
        105 |   using auto_ptr = std::unique_ptr<T>;
            |   ^
      fatal error: too many errors emitted, stopping now [-ferror-limit=]
```

Which was solved using @romanovj 's suggestion to add the `-D_LIBCPP_ENABLE_CXX17_REMOVED_AUTO_PTR` CFLAG to the pip install.

Following his instructions, I was able to get this to work on Android 11 (LineageOS) on the Pixel XL.

**Comment by Serendo** [comment]
pyexiv2 is hard to install on termux under android 13. You can use exiv2 cmd tool directly to add gcamera tags.

`exiv2 -M "reg GCamera http://ns.google.com/photos/1.0/camera/" -M "add Xmp.GCamera.MicroVideo 1" photo.jpg`

works fine for me.

**Comment by pyendluru** [comment]
I'm still getting the same error. Can you please share how exactly the CFLAGS is used in Termux?

![SmartSelect_20241223_043645_Termux](https://github.com/user-attachments/assets/772e3f45-bd12-4ae9-9fbf-41b0cecd6581)

**Comment by mihir-io** [comment]
The py3exiv2 package should now be able to be installed within Termux. The `requirements.py` file has been updated to point to the latest version, which fixes the build issues. The other change was to install the `openssl` package, since `pip` now needs it for SSL auth with PyPI.
